In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split
# Sample dataset
texts=["I love this movie!",
           "This movie is terrible.",
           "The food was amazing.",
           "I hate Mondays.",
           "Great customer service.",
           "The weather today is awful.",
           "I'm feeling happy today.",
           "The new restaurant is disappointing.",
           "The book was captivating.",
           "I'm frustrated with the traffic.",
           "The concert was fantastic.",
           "The service at the hotel was poor.",
           "I'm indifferent about the outcome.",
           "The presentation was boring.",
           "The vacation was unforgettable."]
# Corresponding sentiment labels (0 for negative, 1 for neutral, 2 for positive)
sentiments =[2, 0, 2, 0, 2,
                0, 2, 0, 2, 0,
                2, 0, 1, 0, 2]
from tensorflow.keras.preprocessing.sequence import pad_sequences
# Convert names to numerical representation
tokenizer = Tokenizer(char_level=False)
tokenizer.fit_on_texts(texts)
print("Vocabulary:", tokenizer.word_index)
# Convert names to numerical representation
X = tokenizer.texts_to_sequences(texts)
print(X)
# Pad sequences to a fixed length
max_length = max(len(seq) for seq in X)
X = pad_sequences(X, maxlen=max_length, padding='post')
print(X)
# Convert to numpy array
X = np.array(X)

# One-hot encode genders
#y = np.array([1 if gender == 'male' else 0 for gender in genders])
y=np.array(sentiments)
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(len(tokenizer.word_index))
print(X.shape[1])
# Build SimpleRNN model
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=20, input_length=X.shape[1]))
model.add(SimpleRNN(20))
model.add(Dense(3, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=1, verbose=1)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f'Test Accuracy: {accuracy * 100:.2f}%')

Vocabulary: {'the': 1, 'was': 2, 'is': 3, "i'm": 4, 'i': 5, 'this': 6, 'movie': 7, 'service': 8, 'today': 9, 'love': 10, 'terrible': 11, 'food': 12, 'amazing': 13, 'hate': 14, 'mondays': 15, 'great': 16, 'customer': 17, 'weather': 18, 'awful': 19, 'feeling': 20, 'happy': 21, 'new': 22, 'restaurant': 23, 'disappointing': 24, 'book': 25, 'captivating': 26, 'frustrated': 27, 'with': 28, 'traffic': 29, 'concert': 30, 'fantastic': 31, 'at': 32, 'hotel': 33, 'poor': 34, 'indifferent': 35, 'about': 36, 'outcome': 37, 'presentation': 38, 'boring': 39, 'vacation': 40, 'unforgettable': 41}
[[5, 10, 6, 7], [6, 7, 3, 11], [1, 12, 2, 13], [5, 14, 15], [16, 17, 8], [1, 18, 9, 3, 19], [4, 20, 21, 9], [1, 22, 23, 3, 24], [1, 25, 2, 26], [4, 27, 28, 1, 29], [1, 30, 2, 31], [1, 8, 32, 1, 33, 2, 34], [4, 35, 36, 1, 37], [1, 38, 2, 39], [1, 40, 2, 41]]
[[ 5 10  6  7  0  0  0]
 [ 6  7  3 11  0  0  0]
 [ 1 12  2 13  0  0  0]
 [ 5 14 15  0  0  0  0]
 [16 17  8  0  0  0  0]
 [ 1 18  9  3 19  0  0]
 [ 4 20 21 

In [ ]:
# Sample text data for prediction
texts_to_predict = ["I love this movie!",
                    "I'm feeling sad today.",
                    "The restaurant was okay.",
                    "The concert was amazing!"]
# Convert texts to numerical representation
X_predict = tokenizer.texts_to_sequences(texts_to_predict)
# Pad sequences to a fixed length
X_predict = pad_sequences(X_predict, maxlen=max_length, padding='post')
# Predict sentiment for the texts
predictions = model.predict(X_predict)
# Decode the predictions
sentiment_mapping = {0: 'Negative', 1: 'Neutral', 2: 'Positive'}
decoded_predictions = [sentiment_mapping[np.argmax(pred)] for pred in predictions]
# Display the predicted sentiments
for text, sentiment in zip(texts_to_predict, decoded_predictions):
    print(f'Text: {text} - Predicted Sentiment: {sentiment}')


1/1 [==============================] - 0s 197ms/step
Text: I love this movie! - Predicted Sentiment: Negative
Text: I'm feeling sad today. - Predicted Sentiment: Positive
Text: The restaurant was okay. - Predicted Sentiment: Positive
Text: The concert was amazing! - Predicted Sentiment: Positive
